setting:
  binWidth: 25
  label: 1
  interpolator: 'sitkBSpline'
  resampledPixelSpacing:
  weightingNorm:


imageType:
  Original: {}
  Wavelet: {}
  LBP2D: {}
  Exponential: {}
  Gradient: {}
  Logarithm: {}
  SquareRoot: {}
  Square: {}


featureClass:
  firstorder:
  glcm:
  gldm:
  glszm:
  glrlm:

